name: Make draft release

on:
  workflow_dispatch:

jobs:
  build:
    name: Run build
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:

      - uses: actions/download-artifact@v4

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create --draft ${{ github.ref_name }} --title ${{ github.ref_name }} build/*.jar
