name: Publish to SciJava Maven

on:
  workflow_call:
    inputs:
      release:
        required: false
        type: boolean
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Add release flag if input variable is set
        if: ${{ inputs.release }}
        shell: bash
        run: |
          echo "RELEASE_FLAG='-P release=true'" >> $GITHUB_ENV

      - name: Publish snapshot
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
         arguments: publish -P toolchain=21 $RELEASE_FLAG
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
      - uses: actions/upload-artifact@v3
        if: ${{ inputs.release }}
        with:
          name: ${{ github.event.repository.name }}-release-jar
          path: build/libs
          retention-days: 7
